import { WordProps } from './Words.types';

const wordBank: WordProps[] = [
  {
    spelling: 'ameliorate',
    definition: 'to make better or more tolerable',
    partOfSpeech: 'verb',
    dateLearned: 1610337000,
  },
  {
    spelling: 'anathema',
    definition: 'someone or something that is detested or shunned',
    partOfSpeech: 'noun',
    dateLearned: 1578715080,
  },
  {
    spelling: 'appellation',
    definition: 'a name or title',
    partOfSpeech: 'noun',
    dateLearned: 1610337360,
  },
  {
    spelling: 'aspersion',
    definition: 'an attack on the reputation or integrity of someone or something',
    partOfSpeech: 'noun',
    dateLearned: 1578714240,
  },
  {
    spelling: 'assiduously',
    definition: 'with great care and perseverance',
    partOfSpeech: 'adverb',
    dateLearned: 1578714300,
  },
  {
    spelling: 'autarky',
    definition: 'economic independence or self-sufficiency',
    partOfSpeech: 'noun',
    dateLearned: 1547178000,
  },
  {
    spelling: 'bien-pensants',
    definition: 'a right thinking or orthodox person',
    partOfSpeech: 'noun',
    dateLearned: 1515643140,
  },
  {
    spelling: 'bivouac',
    definition:
      'a temporary camp without tents or cover, used especially by soldiers or mountaineers',
    partOfSpeech: 'noun',
    dateLearned: 1547177940,
  },
  {
    spelling: 'cogitating',
    definition: 'pondering or meditating on',
    partOfSpeech: 'verb',
    dateLearned: 1515642480,
  },
  {
    spelling: 'cognomen',
    definition:
      'an extra personal name given to an ancient Roman citizen; functioning like a nickname',
    partOfSpeech: 'noun',
    dateLearned: 1610337300,
  },
  {
    spelling: 'condign',
    definition: 'appropriate to the punishment of the crime, fitting, deserved',
    partOfSpeech: 'adjective',
    dateLearned: 1578714600,
  },
  {
    spelling: 'contretemps',
    definition: 'minor disagreement or dispute',
    partOfSpeech: 'noun',
    dateLearned: 1515642420,
  },
  {
    spelling: 'contrivance',
    definition: 'an artificial arrangement or development',
    partOfSpeech: 'noun',
    dateLearned: 1547178480,
  },
  {
    spelling: 'cyclamen',
    definition: 'plants of the primrose family having showy nodding flowers',
    partOfSpeech: 'noun',
    dateLearned: 1610337120,
  },
  {
    spelling: 'demiurge',
    definition: 'a being responsible for the creation of the universe',
    partOfSpeech: 'noun',
    dateLearned: 1578715020,
  },
  {
    spelling: 'desiccate',
    definition: 'to dry thoroughly',
    partOfSpeech: 'verb',
    dateLearned: 1578714420,
  },
  {
    spelling: 'ermine',
    definition: 'any of several weasels whose coats become white in winter',
    partOfSpeech: 'noun',
    dateLearned: 1547179020,
  },
  {
    spelling: 'exigency',
    definition: 'an urgent need or demand',
    partOfSpeech: 'noun',
    dateLearned: 1547179140,
  },
  {
    spelling: 'festoon',
    definition: 'to adorn a place with ribbons, garlands, or other decorations',
    partOfSpeech: 'verb',
    dateLearned: 1547178360,
  },
  {
    spelling: 'furtive',
    definition:
      'attempting to avoid notice or attention, typically because of guilt or a belief that discovery would lead to trouble; secretive',
    partOfSpeech: 'adjective',
    dateLearned: 1547178060,
  },
  {
    spelling: 'fusillade',
    definition:
      'a series of shots fired or missiles thrown all at the same time or in quick succession',
    partOfSpeech: 'noun',
    dateLearned: 1578714780,
  },
  {
    spelling: 'gauche',
    definition: 'lacking social experience or grace',
    partOfSpeech: 'adjective',
    dateLearned: 1515642600,
  },
  {
    spelling: 'hegemonic',
    definition: 'having complete dominion or power',
    partOfSpeech: 'noun',
    dateLearned: 1610337060,
  },
  {
    spelling: 'iconoclast',
    definition: 'a person who attacks cherished beliefs or institutions',
    partOfSpeech: 'noun',
    dateLearned: 1578714840,
  },
  {
    spelling: 'impinge',
    definition:
      'to have an impact on or make an impression; to encroach or infringe upon',
    partOfSpeech: 'verb',
    dateLearned: 1578714180,
  },
  {
    spelling: 'improvident',
    definition: 'not foreseeing and providing for the future',
    partOfSpeech: 'adjective',
    dateLearned: 1547178540,
  },
  {
    spelling: 'inimitable',
    definition: 'so good or unusual as to be impossible to copy; unique',
    partOfSpeech: 'adjective',
    dateLearned: 1578714720,
  },
  {
    spelling: 'iniquity',
    definition: 'immoral or grossly unfair behavior',
    partOfSpeech: 'noun',
    dateLearned: 1610337420,
  },
  {
    spelling: 'intransigence',
    definition: "refusal to change one's views or to agree about something",
    partOfSpeech: 'noun',
    dateLearned: 1547178180,
  },
  {
    spelling: 'jingoism',
    definition:
      'extreme patriotism, most often demonstrated via aggressive foreign policy',
    partOfSpeech: 'noun',
    dateLearned: 1630472400,
  },
  {
    spelling: 'luddite',
    definition:
      'someone who is opposed or resistant to new technologies or technological change',
    partOfSpeech: 'noun',
    dateLearned: 1578714960,
  },
  {
    spelling: 'melange',
    definition: 'a mixture or medley',
    partOfSpeech: 'noun',
    dateLearned: 1578714480,
  },
  {
    spelling: 'nascent',
    definition:
      'coming into existence and beginning to display signs of future potential',
    partOfSpeech: 'adjective',
    dateLearned: 1578715140,
  },
  {
    spelling: 'obsequious',
    definition: 'marked by or exhibiting a fawning attentiveness',
    partOfSpeech: 'adjective',
    dateLearned: 1547178900,
  },
  {
    spelling: 'parsimonious',
    definition: 'unwilling to spend money or use resources',
    partOfSpeech: 'adjective',
    dateLearned: 1515643020,
  },
  {
    spelling: 'pedagogy',
    definition: 'the art, science, or profession of teaching',
    partOfSpeech: 'noun',
    dateLearned: 1547178720,
  },
  {
    spelling: 'pernicious',
    definition: 'having a harmful effect in a gradual or subtle manner',
    partOfSpeech: 'adjective',
    dateLearned: 1578714660,
  },
  {
    spelling: 'perspicacious',
    definition: 'having a ready insight into and understanding of things',
    partOfSpeech: 'adjective',
    dateLearned: 1610337540,
  },
  {
    spelling: 'pollyannish',
    definition:
      'irrepressibly or excessively optimistic; capable of seeing good in anyone',
    partOfSpeech: 'adjective',
    dateLearned: 1515642780,
  },
  {
    spelling: 'presage',
    definition: 'something that foreshadows or portends a future event',
    partOfSpeech: 'noun',
    dateLearned: 1515642900,
  },
  {
    spelling: 'prevaricate',
    definition: 'to deviate from the truth',
    partOfSpeech: 'verb',
    dateLearned: 1515642360,
  },
  {
    spelling: 'prig',
    definition: 'one who offends or irritates',
    partOfSpeech: 'noun',
    dateLearned: 1610337180,
  },
  {
    spelling: 'prolegomenon',
    definition:
      'a formal essay or critical discussion serving to introduce and interpret an extended work',
    partOfSpeech: 'noun',
    dateLearned: 1610337240,
  },
  {
    spelling: 'putative',
    definition: 'generally considered or reputed to be',
    partOfSpeech: 'adjective',
    dateLearned: 1578714360,
  },
  {
    spelling: 'querulous',
    definition: 'habitually complaining',
    partOfSpeech: 'adjective',
    dateLearned: 1547178840,
  },
  {
    spelling: 'reconnoiter',
    definition: 'to make a military observation of (a region)',
    partOfSpeech: 'verb',
    dateLearned: 1547178300,
  },
  {
    spelling: 'recrimination',
    definition: 'a retaliatory accusation',
    partOfSpeech: 'noun',
    dateLearned: 1515642660,
  },
  {
    spelling: 'remonstrance',
    definition: 'an earnest presentation of reasons for opposition or grievance',
    partOfSpeech: 'noun',
    dateLearned: 1515643080,
  },
  {
    spelling: 'rivulet',
    definition: 'a small stream',
    partOfSpeech: 'noun',
    dateLearned: 1515642720,
  },
  {
    spelling: 'scansion',
    definition: 'the action of scanning a line of verse to determine its rhythm',
    partOfSpeech: 'noun',
    dateLearned: 1547178240,
  },
  {
    spelling: 'seiche',
    definition:
      'an oscillation of the surface of a landlocked body of water that varies in period from a few minutes to several hours',
    partOfSpeech: 'noun',
    dateLearned: 1547178600,
  },
  {
    spelling: 'semaphore',
    definition:
      'a variable or abstract data type used to control access to a common resource',
    partOfSpeech: 'noun',
    dateLearned: 1515642960,
  },
  {
    spelling: 'shibboleth',
    definition:
      'a custom, principle, or belief distinguishing a particular class or group of people, especially a long-standing one regarded as outmoded or no longer important',
    partOfSpeech: 'noun',
    dateLearned: 1578714900,
  },
  {
    spelling: 'sidled',
    definition: 'to move sideways',
    partOfSpeech: 'verb',
    dateLearned: 1515642540,
  },
  {
    spelling: 'slovenly',
    definition: 'careless; excessively casual',
    partOfSpeech: 'adjective',
    dateLearned: 1547178420,
  },
  {
    spelling: 'somnolence',
    definition: 'the quality or state of being drowsy',
    partOfSpeech: 'noun',
    dateLearned: 1547178960,
  },
  {
    spelling: 'soporific',
    definition: 'causing or tending to cause sleep',
    partOfSpeech: 'adjective',
    dateLearned: 1547178780,
  },
  {
    spelling: 'suffuse',
    definition: 'gradually spread through or over',
    partOfSpeech: 'verb',
    dateLearned: 1610337480,
  },
  {
    spelling: 'synodic',
    definition: 'relating to conjunction',
    partOfSpeech: 'adjective',
    dateLearned: 1547179080,
  },
  {
    spelling: 'timorously',
    definition: 'of a timid disposition',
    partOfSpeech: 'adjective',
    dateLearned: 1547178660,
  },
  {
    spelling: 'umbrage',
    definition: 'offense or annoyance',
    partOfSpeech: 'noun',
    dateLearned: 1578714540,
  },
  {
    spelling: 'vittles',
    definition: 'provisions or eatables',
    partOfSpeech: 'noun',
    dateLearned: 1547178120,
  },
  {
    spelling: 'vituperation',
    definition: 'noun that refers to critical or abusive language',
    partOfSpeech: 'noun',
    dateLearned: 1515642840,
  },
  {
    spelling: 'abscond',
    definition: 'to leave hurriedly, usually to avoid detection',
    partOfSpeech: 'verb',
    dateLearned: 1658335722,
  },
  {
    spelling: 'rapacious',
    definition: 'aggressively greedy',
    partOfSpeech: 'adjective',
    dateLearned: 1658335691,
  },
  {
    spelling: 'abeyance',
    definition: 'a state of temporary inactivity',
    partOfSpeech: 'noun',
    dateLearned: 1658500875,
  },
  {
    spelling: 'maudlin',
    definition: 'overly sentimental',
    partOfSpeech: 'adjective',
    dateLearned: 1658500876,
  },
  {
    spelling: 'concomitant',
    definition: 'accompanying in a subordinate manner',
    partOfSpeech: 'adjective',
    dateLearned: 1658500877,
  },
  {
    spelling: 'geodesic',
    definition: 'comprised of light and straight structural elements',
    partOfSpeech: 'adjective',
    dateLearned: 1658500878,
  },
  {
    spelling: 'laconic',
    definition: 'concise almost to the point of rudeness',
    partOfSpeech: 'adjective',
    dateLearned: 1658500879,
  },
  {
    spelling: 'embochure',
    definition: 'the position and use of the mouth when playing a wind instrument',
    partOfSpeech: 'noun',
    dateLearned: 1658500880,
  },
  {
    spelling: 'couture',
    definition: 'the business of creating and selling fashionable, custom clothing',
    partOfSpeech: 'noun',
    dateLearned: 1658500881,
  },
  {
    spelling: 'licentious',
    definition: 'lacking legal or moral restraints',
    partOfSpeech: 'adjective',
    dateLearned: 1658500882,
  },
  {
    spelling: 'pareidolia',
    definition:
      'the tendency to discern a meaningful image in a random visual pattern',
    partOfSpeech: 'noun',
    dateLearned: 1658500883,
  },
  {
    spelling: 'diegetic',
    definition:
      'existing within the world of a narrative to the point the characters within the world are aware of it',
    partOfSpeech: 'adjective',
    dateLearned: 1658500884,
  },
  {
    spelling: 'castigate',
    definition: 'to subject to extreme punishment or criticism',
    partOfSpeech: 'verb',
    dateLearned: 1658500885,
  },
  {
    spelling: 'roentgen',
    definition: 'a unit of ionizing radiation',
    partOfSpeech: 'noun',
    dateLearned: 1658500886,
  },
  {
    spelling: 'chignon',
    definition: 'a knot of hair worn near the neck',
    partOfSpeech: 'noun',
    dateLearned: 1659717384,
  },
  {
    spelling: 'crepitus',
    definition: 'the grating sound from friction between bone and cartilage',
    partOfSpeech: 'noun',
    dateLearned: 1659990984,
  },
  {
    spelling: 'pallor',
    definition: 'paleness of the face',
    partOfSpeech: 'noun',
    dateLearned: 1659990996,
  },
  {
    spelling: 'macadam',
    definition: 'roadway or pavement with a binder',
    partOfSpeech: 'noun',
    dateLearned: 1659994584,
  },
  {
    spelling: 'suborn',
    definition: 'to bribe someone to commit an unlawful deed',
    partOfSpeech: 'verb',
    dateLearned: 1660422984,
  },
  {
    spelling: 'emoluments',
    definition: 'a salary or fee from employment or office',
    partOfSpeech: 'noun',
    dateLearned: 1660422991,
  },
  {
    spelling: 'oeuvre',
    definition: 'the works of an artists regarded collectively',
    partOfSpeech: 'noun',
    dateLearned: 1661595986,
  },
  {
    spelling: 'manacle',
    definition: 'a shackle for the wrist, used as a restraint',
    partOfSpeech: 'noun',
    dateLearned: 1661801297,
  },
  {
    spelling: 'cordon',
    definition: 'a line of people or objects preventing passage',
    partOfSpeech: 'noun',
    dateLearned: 1661880538,
  },
  {
    spelling: 'anechoic',
    definition: 'free from echo or reverb',
    partOfSpeech: 'adjective',
    dateLearned: 1661966938,
  },
  {
    spelling: 'abrogate',
    definition: 'to abolish via action by an authority',
    partOfSpeech: 'verb',
    dateLearned: 1662398938,
  },
  {
    spelling: 'petrichor',
    definition: 'a pleasant aroma from the first rain following a dry period',
    partOfSpeech: 'noun',
    dateLearned: 1663059577,
  },
  {
    spelling: 'irasicble',
    definition: 'hot-tempered or easily angered',
    partOfSpeech: 'adjective',
    dateLearned: 1663777110,
  },
  {
    spelling: 'tussock',
    definition: 'a compact tuft of grass or sedge',
    partOfSpeech: 'noun',
    dateLearned: 1663949910,
  },
  {
    spelling: 'diffident',
    definition: 'shy due to a lack of self-confidence',
    partOfSpeech: 'adjective',
    dateLearned: 1665753056,
  },
  {
    spelling: 'treacle',
    definition: 'a think, dark syrup made from refined sugar; mainly British',
    partOfSpeech: 'noun',
    dateLearned: 1667316656,
  },
  {
    spelling: 'frontispiece',
    definition: 'an illustration that faces the title page of a book',
    partOfSpeech: 'noun',
    dateLearned: 1668612656,
  },
  {
    spelling: 'inculcate',
    definition: 'to instill via frequent instruction and repition',
    partOfSpeech: 'verb',
    dateLearned: 1671291056,
  },
  {
    spelling: 'anisette',
    definition: 'a colorless sweet liequeur made from aniseed',
    partOfSpeech: 'noun',
    dateLearned: 1673451056,
  },
  {
    spelling: 'ablutions',
    definition:
      'the building on a military base that contains bathing and toilet facilities',
    partOfSpeech: 'noun',
    dateLearned: 1673537456,
  },
  {
    spelling: 'jodhpur',
    definition: 'an ankle-high boot that is buckled at the side',
    partOfSpeech: 'noun',
    dateLearned: 1674574256,
  },
  {
    spelling: 'mellifluous',
    definition: 'having a smooth flow',
    partOfSpeech: 'adjective',
    dateLearned: 1675978531,
  },
  {
    spelling: 'cognoscenti',
    definition: 'one with expert knowledge in a subject or field',
    partOfSpeech: 'noun',
    dateLearned: 1675978591,
  },
  {
    spelling: 'parvenu',
    definition:
      'one that has suddenly attained a position of power or wealth but has not earned the associated respect or dignity',
    partOfSpeech: 'noun',
    dateLearned: 1675978651,
  },
  {
    spelling: 'garrulous',
    definition: 'prone to rambling; annoyingly talkative',
    partOfSpeech: 'adjective',
    dateLearned: 1675978711,
  },
  {
    spelling: 'crepuscular',
    definition: 'occurring during twilight',
    partOfSpeech: 'adjective',
    dateLearned: 1675978771,
  },
  {
    spelling: 'chortens',
    definition: 'a Tibetan Buddhist monument',
    partOfSpeech: 'noun',
    dateLearned: 1675978831,
  },
  {
    spelling: 'brocade',
    definition: 'a fabric containing raised designs; typically in silver and gold',
    partOfSpeech: 'noun',
    dateLearned: 1675978891,
  },
  {
    spelling: 'antipodal',
    definition: 'situated at the opposite side of the earth',
    partOfSpeech: 'adjective',
    dateLearned: 1675978951,
  },
  {
    spelling: 'surfeit',
    definition: 'an overabundant supply',
    partOfSpeech: 'noun',
    dateLearned: 1675979011,
  },
  {
    spelling: 'suppurate',
    definition: 'to form or discharge pus',
    partOfSpeech: 'verb',
    dateLearned: 1675979071,
  },
  {
    spelling: 'peripatetic',
    definition: 'moving or traveling from place to place',
    partOfSpeech: 'adjective',
    dateLearned: 1675979131,
  },
  {
    spelling: 'harangue',
    definition: 'a ranting speech',
    partOfSpeech: 'noun',
    dateLearned: 1676065231,
  },
  {
    spelling: 'paucity',
    definition: 'smallness of quantity',
    partOfSpeech: 'noun',
    dateLearned: 1676065291,
  },
  {
    spelling: 'impecunious',
    definition: 'habitually having little to no money',
    partOfSpeech: 'adjective',
    dateLearned: 1676065351,
  },
  {
    spelling: 'incipient',
    definition: 'to become apparent',
    partOfSpeech: 'adjective',
    dateLearned: 1676065411,
  },
  {
    spelling: 'hosannas',
    definition: 'cries of acclamation or adoration',
    partOfSpeech: 'interjection',
    dateLearned: 1676151811,
  },
  {
    spelling: 'massif',
    definition: 'a principal mountain pass',
    partOfSpeech: 'noun',
    dateLearned: 1676151812,
  },
  {
    spelling: 'augur',
    definition: 'to foretell events usually via omens',
    partOfSpeech: 'verb',
    dateLearned: 1676151931,
  },
  /*  {
    spelling: 'mirabile visu',
    definition: 'wonderful to behold (latin)',
    partOfSpeech: 'phrase',
    dateLearned: 1676151991,
  }, */
  {
    spelling: 'hors de combat',
    definition: 'out of combat; disabled',
    partOfSpeech: 'adjective',
    dateLearned: 1676152051,
  },
  {
    spelling: 'fecundity',
    definition: 'the ability to produce ample offspring or ideas',
    partOfSpeech: 'noun',
    dateLearned: 1676152171,
  },
  {
    spelling: 'penumbra',
    definition: 'something that covers or obscures',
    partOfSpeech: 'noun',
    dateLearned: 1676152231,
  },
  {
    spelling: 'orrery',
    definition:
      'an apparatus displaying the relative positions and motions of bodies in a solar system via clockwork',
    partOfSpeech: 'noun',
    dateLearned: 1677130381,
  },
  {
    spelling: 'inchoate',
    definition: 'not fully formed or developed',
    partOfSpeech: 'adjective',
    dateLearned: 1679951407,
  },
  {
    spelling: 'epistolary',
    definition: 'in the form of letters (literary works)',
    partOfSpeech: 'adjective',
    dateLearned: 1680372607,
  },
  {
    spelling: 'parturition',
    definition: 'the act of giving birth to young',
    partOfSpeech: 'noun',
    dateLearned: 1681755007,
  },
  {
    spelling: 'frond',
    definition: 'the leaflike part of a palm or fern',
    partOfSpeech: 'noun',
    dateLearned: 1682449807,
  },
  {
    spelling: 'extirpate',
    definition: 'to destroy or remove completely',
    partOfSpeech: 'verb',
    dateLearned: 1683666607,
  },
  {
    spelling: 'stentorian',
    definition: 'loud and powerful; relating to the voice',
    partOfSpeech: 'adjective',
    dateLearned: 1683670207,
  },
  {
    spelling: 'redolent',
    definition: 'strongly reminiscent or suggestive of something',
    partOfSpeech: 'adjective',
    dateLearned: 1683745807,
  },
  {
    spelling: 'lorgnette',
    definition:
      'a pair of glasses held in front of the eyes via a long handle to one side',
    partOfSpeech: 'noun',
    dateLearned: 1683749407,
  },
  {
    spelling: 'atavistic',
    definition: 'relating to something ancient or ancestral',
    partOfSpeech: 'adjective',
    dateLearned: 1684173049,
  },
  {
    spelling: 'lassitude',
    definition: 'physical or mental weariness',
    partOfSpeech: 'noun',
    dateLearned: 1684176649,
  },
  {
    spelling: 'alluvium',
    definition:
      'a deposit of sendiment left by flowing water; usually results in fertile soil',
    partOfSpeech: 'noun',
    dateLearned: 1684180249,
  },
  {
    spelling: 'trunnion',
    definition: 'a point on which something can be rotated or tilted',
    partOfSpeech: 'noun',
    dateLearned: 1684183849,
  },
  {
    spelling: 'passerine',
    definition:
      'a bird of the order Passeriformes, commonly known as perching birds',
    partOfSpeech: 'noun',
    dateLearned: 1684187449,
  },
  {
    spelling: 'filigree',
    definition: 'ornamental work of fine wire, usually gold or silver',
    partOfSpeech: 'noun',
    dateLearned: 1684395380,
  },
  {
    spelling: 'coruscating',
    definition: 'flashing or sparkling',
    partOfSpeech: 'adjective',
    dateLearned: 1684481780,
  },
  {
    spelling: 'anhedonia',
    definition: 'the inability to feel pleasure',
    partOfSpeech: 'noun',
    dateLearned: 1684827380,
  },
  {
    spelling: 'indigent',
    definition: 'poor; needy',
    partOfSpeech: 'adjective',
    dateLearned: 1686017706,
  },
  {
    spelling: 'excoriate',
    definition:
      'to censure or criticize (formal); to damage or remove part of the skin (medicine)',
    partOfSpeech: 'verb',
    dateLearned: 1686860459,
  },
  {
    spelling: 'hirsute',
    definition: 'hairy',
    partOfSpeech: 'adjective',
    dateLearned: 1687206059,
  },
  {
    spelling: 'cavalcade',
    definition:
      'a formal procession of people walking, riding horses or in vehicles',
    partOfSpeech: 'noun',
    dateLearned: 1687282570,
  },
  {
    spelling: 'bucolic',
    definition: 'relating to the pleasant characteristics of the countryside',
    partOfSpeech: 'adjective',
    dateLearned: 1687368970,
  },
  {
    spelling: 'menarche',
    definition: 'the first occurrence of menstruation',
    partOfSpeech: 'noun',
    dateLearned: 1686860644,
  },
  {
    spelling: 'docent',
    definition: 'a person who acts as a guide, usually on a voluntary basis',
    partOfSpeech: 'noun',
    dateLearned: 1688244822,
  },
  {
    spelling: 'suppletion',
    definition:
      'the occurrence of an unrelated form to fill a gap in conjugation; such as went as the past tense to gold',
    partOfSpeech: 'noun',
    dateLearned: 1688676822,
  },
  {
    spelling: 'abjure',
    definition: 'to solemnly renounce a belief or cause',
    partOfSpeech: 'verb',
    dateLearned: 1688681455,
  },
  {
    spelling: 'poultice',
    definition:
      'a soft, moist mass of material applied to the body to alleviate soreness and inflammation; usually plant or flour based',
    partOfSpeech: 'noun',
    dateLearned: 1688681515,
  },
  {
    spelling: 'extemporize',
    definition:
      'to compose, perform or produce something without preparation; improvise',
    partOfSpeech: 'verb',
    dateLearned: 1688681575,
  },
  {
    spelling: 'philter',
    definition: 'a love potion',
    partOfSpeech: 'noun',
    dateLearned: 1688681695,
  },
  {
    spelling: 'morass',
    definition: 'an area of muddy ground',
    partOfSpeech: 'noun',
    dateLearned: 1688681815,
  },
  {
    spelling: 'bellicosity',
    definition: 'a natural disposition towards violence and fighting',
    partOfSpeech: 'noun',
    dateLearned: 1688768215,
  },
  {
    spelling: 'conviviality',
    definition: 'the quality of being friendly and full of life',
    partOfSpeech: 'noun',
    dateLearned: 1688854615,
  },
  {
    spelling: 'defalcation',
    definition:
      'the act of embezzling or failture to meet a promise or an expectation',
    partOfSpeech: 'noun',
    dateLearned: 1688854735,
  },
  {
    spelling: 'mien',
    definition: "someone's look or manner",
    partOfSpeech: 'noun',
    dateLearned: 1688941135,
  },
  {
    spelling: 'bailiwick',
    definition: "one's area of interest or sphere of operations",
    partOfSpeech: 'noun',
    dateLearned: 1689027535,
  },
  {
    spelling: 'ribald',
    definition: 'referring to sexual matters in an irreverent way',
    partOfSpeech: 'adjective',
    dateLearned: 1689031135,
  },
  {
    spelling: 'expurgated',
    definition: 'having had objectionable matter removed from a text or an account',
    partOfSpeech: 'adjective',
    dateLearned: 1689034735,
  },
  {
    spelling: 'carom',
    definition: 'to strike and rebound',
    partOfSpeech: 'verb',
    dateLearned: 1689038335,
  },
  {
    spelling: 'panoply',
    definition: 'a splendid display and or collection of things',
    partOfSpeech: 'noun',
    dateLearned: 1689106245,
  },
  {
    spelling: 'mandamus',
    definition: 'a judicial writ serving as a command to an inferior court',
    partOfSpeech: 'noun',
    dateLearned: 1689109845,
  },
  {
    spelling: 'metaplasm',
    definition:
      'the alteration of regular verbal, grammatical or rhetorical structure via transposition of letters or syllables',
    partOfSpeech: 'noun',
    dateLearned: 1689117045,
  },
  {
    spelling: 'desultory',
    definition: 'lacking a plan, purpose or enthusiasm',
    partOfSpeech: 'adjective',
    dateLearned: 1689199088,
  },
  {
    spelling: 'elide',
    definition: 'to omit a sound or syllable when speaking',
    partOfSpeech: 'verb',
    dateLearned: 1689285488,
  },
  {
    spelling: 'garret',
    definition: 'a top-floor or attic room; typically small and dismal',
    partOfSpeech: 'noun',
    dateLearned: 1689289088,
  },
  {
    spelling: 'plenary',
    definition: 'unqualified yet absolute; in reference to powers',
    partOfSpeech: 'adjective',
    dateLearned: 1689461888,
  },
  {
    spelling: 'florid',
    definition: 'having a red or flushed complexion',
    partOfSpeech: 'adjective',
    dateLearned: 1689465488,
  },
  {
    spelling: 'moribund',
    definition: 'at the point of death',
    partOfSpeech: 'adjective',
    dateLearned: 1689551888,
  },
  {
    spelling: 'susurration',
    definition: 'whispering or rustling',
    partOfSpeech: 'noun',
    dateLearned: 1689798545,
  },
  {
    spelling: 'bole',
    definition: 'the trunk of a tree',
    partOfSpeech: 'noun',
    dateLearned: 1689884945,
  },
  {
    spelling: 'stodgy',
    definition: 'dull and uninspired',
    partOfSpeech: 'adjective',
    dateLearned: 1690230545,
  },
  {
    spelling: 'mottle',
    definition: 'to mark with spots or smears of color',
    partOfSpeech: 'verb',
    dateLearned: 1690295345,
  },
  {
    spelling: 'libation',
    definition: 'a drink poured as an offering to a higher being',
    partOfSpeech: 'noun',
    dateLearned: 1695074953,
  },
  {
    spelling: 'verdigris',
    definition: 'a green/bluish deposit formed on copper, brass or bronze surfaces',
    partOfSpeech: 'noun',
    dateLearned: 1695593353,
  },
  {
    spelling: 'cubit',
    definition:
      'an ancient measure of length; approximately the length of a forearm',
    partOfSpeech: 'noun',
    dateLearned: 1695604153,
  },
  {
    spelling: 'seneschal',
    definition: 'the steward of a medieval great house',
    partOfSpeech: 'noun',
    dateLearned: 1695607753,
  },
  {
    spelling: 'baldric',
    definition: 'a belt for a sword or weapon; worn over the shoulder',
    partOfSpeech: 'noun',
    dateLearned: 1695611353,
  },
  {
    spelling: 'coracle',
    definition:
      'a small, round boat made of wickerwork and covered with a watertight material',
    partOfSpeech: 'noun',
    dateLearned: 1695870553,
  },
  {
    spelling: 'limpets',
    definition:
      'a group of aquatic snails with a conical shell and a strong, muscular foot',
    partOfSpeech: 'noun',
    dateLearned: 1695870554,
  },
  {
    spelling: 'merlon',
    definition: 'the solid part of an embattled parapet between two embrasures',
    partOfSpeech: 'noun',
    dateLearned: 1696388953,
  },
  {
    spelling: 'alembic',
    definition: 'a distilling apparatus',
    partOfSpeech: 'noun',
    dateLearned: 1696475353,
  },
  {
    spelling: 'bier',
    definition:
      'a movable frame that a coffin or corpse is placed upon prior to a burial or cremation',
    partOfSpeech: 'noun',
    dateLearned: 1696475413,
  },
  {
    spelling: 'pennon',
    definition: 'a long, triangular streamer attached to the head of a lance',
    partOfSpeech: 'noun',
    dateLearned: 1696871413,
  },
  {
    spelling: 'quintain',
    definition: 'a post set up as a mark in tilting with a lance',
    partOfSpeech: 'noun',
    dateLearned: 1697044213,
  },
  {
    spelling: 'ensorcell',
    definition: 'to enchant or fascinate',
    partOfSpeech: 'verb',
    dateLearned: 1697389813,
  },
  {
    spelling: 'caparison',
    definition: "an ornamental covering on a horse's saddle or harness",
    partOfSpeech: 'noun',
    dateLearned: 1697393413,
  },
  {
    spelling: 'gelid',
    definition: 'extremely cold',
    partOfSpeech: 'adjective',
    dateLearned: 1697739013,
  },
  {
    spelling: 'paroxysm',
    definition: 'a sudden attack/expression of a particular emotion',
    partOfSpeech: 'noun',
    dateLearned: 1697998213,
  },
  {
    spelling: 'ponass',
    definition: 'to cook fish over a fire with minimal equipment; usually trout',
    partOfSpeech: 'verb',
    dateLearned: 1697998213,
  },
  {
    spelling: 'gobbet',
    definition: 'a piece or lump of flesh',
    partOfSpeech: 'noun',
    dateLearned: 1698343813,
  },
  {
    spelling: 'gravid',
    definition: 'full of meaning or a specified quality',
    partOfSpeech: 'adjective',
    dateLearned: 1698347413,
  },
  {
    spelling: 'tessellate',
    definition: 'to decorate or cover with a pattern of repeated shapes',
    partOfSpeech: 'verb',
    dateLearned: 1698599413,
  },
  {
    spelling: 'doff',
    definition: "to take off one's hat as a greeting and show of respect",
    partOfSpeech: 'verb',
    dateLearned: 1698772213,
  },
  {
    spelling: 'serried',
    definition: 'standing close together',
    partOfSpeech: 'adjective',
    dateLearned: 1699467013,
  },
  {
    spelling: 'charnel',
    definition: 'associated with death',
    partOfSpeech: 'adjective',
    dateLearned: 1699553413,
  },
  {
    spelling: 'harridan',
    definition: 'a strict, bossy old woman',
    partOfSpeech: 'noun',
    dateLearned: 1699557013,
  },
  {
    spelling: 'mendicant',
    definition: 'a beggar',
    partOfSpeech: 'noun',
    dateLearned: 1699729813,
  },
  {
    spelling: 'tonsure',
    definition: "to shave the hair on top of a monk's head",
    partOfSpeech: 'verb',
    dateLearned: 1699733413,
  },
  {
    spelling: 'weal',
    definition: 'a red, swollen mark left on the flesh as a result of a blow',
    partOfSpeech: 'noun',
    dateLearned: 1700165413,
  },
  {
    spelling: 'cozen',
    definition: 'to trick or deceive',
    partOfSpeech: 'verb',
    dateLearned: 1700424613,
  },
  {
    spelling: 'hostler',
    definition:
      'someone employed to look after the horses of people staying at an inn',
    partOfSpeech: 'noun',
    dateLearned: 1700511013,
  },
  {
    spelling: 'lissome',
    definition: 'thin, supple and graceful',
    partOfSpeech: 'adjective',
    dateLearned: 1700514613,
  },
  {
    spelling: 'slattern',
    definition: 'a dirty, untidy woman',
    partOfSpeech: 'noun',
    dateLearned: 1700590213,
  },
  {
    spelling: 'lambent',
    definition: 'glowing or flickering with a soft radiance',
    partOfSpeech: 'adjective',
    dateLearned: 1700763013,
  },
  {
    spelling: 'tureen',
    definition: 'a deep and covered bowl used for serving foods',
    partOfSpeech: 'noun',
    dateLearned: 1700766613,
  },
  {
    spelling: 'inimical',
    definition: 'unfriendly; hostile',
    partOfSpeech: 'adjective',
    dateLearned: 1701717013,
  },
  {
    spelling: 'baluster',
    definition:
      'an upright support, often a vertical moulded shaft found in stairways',
    partOfSpeech: 'noun',
    dateLearned: 1701889813,
  },
  {
    spelling: 'pellucid',
    definition: 'translucently clear',
    partOfSpeech: 'adjective',
    dateLearned: 1701976213,
  },
  {
    spelling: 'mawkish',
    definition: 'sentimental in a feeble way',
    partOfSpeech: 'adjective',
    dateLearned: 1701979813,
  },
  {
    spelling: 'crenellations',
    definition: 'the battlements of a castle',
    partOfSpeech: 'noun',
    dateLearned: 1701983413,
  },
  {
    spelling: 'obeisance',
    definition: 'a gesture of deferential respect such as a bow or curtsy',
    partOfSpeech: 'noun',
    dateLearned: 1702145413,
  },
  {
    spelling: 'caisson',
    definition: 'a large watertight chamber that is open at the bottom',
    partOfSpeech: 'noun',
    dateLearned: 1702149013,
  },
  {
    spelling: 'catafalque',
    definition:
      'a decorated wooden framework supporting a coffin of a distinguished person',
    partOfSpeech: 'noun',
    dateLearned: 1702152613,
  },
  {
    spelling: 'caliphate',
    definition:
      'an institution under the leadership of an Islamic steward who is considered as a successor to the Islamic prophet Muhammad and the leader of the Muslim world',
    partOfSpeech: 'noun',
    dateLearned: 1702957066,
  },
  {
    spelling: 'japery',
    definition: 'the act of acting foolish and mocking',
    partOfSpeech: 'noun',
    dateLearned: 1703043466,
  },
  {
    spelling: 'unguent',
    definition: 'a soft, viscous substance used as an ointment or lubricant',
    partOfSpeech: 'noun',
    dateLearned: 1704243531,
  },
  {
    spelling: 'nostrum',
    definition: 'an ineffective medicine prepared by an unqualified individual',
    partOfSpeech: 'noun',
    dateLearned: 1704416331,
  },
  {
    spelling: 'caterwauling',
    definition: 'to make a shrill howling or wailing noise',
    partOfSpeech: 'verb',
    dateLearned: 1705452398,
  },
];

export { wordBank };
