import {
  Books,
  BrandDiscord,
  BrandFacebook,
  BrandFigma,
  BrandGithub,
  BrandInstagram,
  BrandReddit,
  BrandSpotify,
  BrandTwitch,
  BrandTwitter,
  DeviceTvOld,
  LetterC,
  Mail,
  Movie,
  School,
} from 'tabler-icons-react';
import { SocialPlatformProps } from './Social.types';

const SocialUrls = {
  email: 'mailto:adamjnav@gmail.com',
  centered: 'https://centered.app/u/adamjnavarro',
  discord: 'https://discordapp.com/users/862719697422254100',
  facebook: 'https://facebook.com/adamjosephnavarro',
  figma: 'https://figma.com/@adamjnavarro',
  github: 'https://github.com/AdamJNavarro',
  instagram: 'https://instagram.com/adamjnavarro',
  letterboxd: 'https://letterboxd.com/adamjnavarro',
  literal: 'https://literal.club/adamjnavarro',
  rawg: 'https://rawg.io/@adamjnavarro',
  reddit: 'https://reddit.com/user/adamjnav',
  spotify: 'https://open.spotify.com/user/adamjosephnavarro',
  trakt: 'https://trakt.tv/users/adamjnavarro',
  twitch: 'https://twitch.tv/adamjnavarro',
  twitter: 'https://twitter.com/AdamJNavarro',
  udemy: 'https://udemy.com/user/adamjnavarro',
  youtube: 'https://youtube.com/channel/UCWiK8RcF4i56z2ZEMjJmMXw',
};

const SocialPlatforms: SocialPlatformProps[] = [
  {
    icon: Mail,
    href: SocialUrls.email,
    label: 'Email',
    important: true,
    show: true,
  },
  {
    icon: BrandGithub,
    href: SocialUrls.github,
    label: 'Github',
    important: true,
    show: true,
  },
  {
    icon: BrandInstagram,
    href: SocialUrls.instagram,
    label: 'Instagram',
    important: true,
    show: true,
  },
  {
    icon: BrandTwitter,
    href: SocialUrls.twitter,
    label: 'Twitter',
    important: true,
    show: true,
  },
  {
    icon: LetterC,
    href: SocialUrls.centered,
    label: 'Centered',
    show: true,
  },
  {
    icon: BrandDiscord,
    href: SocialUrls.discord,
    label: 'Discord',
    show: false,
  },
  {
    icon: BrandFacebook,
    href: SocialUrls.facebook,
    label: 'Facebook',
    show: true,
  },
  {
    icon: BrandFigma,
    href: SocialUrls.figma,
    label: 'Figma',
    show: false,
  },
  {
    icon: Movie,
    href: SocialUrls.letterboxd,
    label: 'Letterboxd',
    show: true,
  },
  {
    icon: Books,
    href: SocialUrls.literal,
    label: 'Literal',
    show: true,
  },
  {
    icon: BrandReddit,
    href: SocialUrls.reddit,
    label: 'Reddit',
    show: false,
  },
  {
    icon: BrandSpotify,
    href: SocialUrls.spotify,
    label: 'Spotify',
    show: true,
  },
  {
    icon: DeviceTvOld,
    href: SocialUrls.trakt,
    label: 'Trakt.tv',
    show: true,
  },
  {
    icon: BrandTwitch,
    href: SocialUrls.twitch,
    label: 'Twitch',
    show: false,
  },
  {
    icon: School,
    href: SocialUrls.udemy,
    label: 'Udemy',
    show: false,
  },
];

export { SocialUrls, SocialPlatforms };
